### ISSUE TITLE
Classic league - table rows are blank

### ISSUE THREAD

**Issue by griffster** [jeppe-smith/better-fpl#8]
Firstly, thank you for your awesome extension. It's been invaluable.

However, I've been having issues in the last few weeks. Chrome Version 56.0.2924.87 (64-bit) throwing the below error and the additional mini (classic) leagues table columns/rows are unpopolated.

![image](https://cloud.githubusercontent.com/assets/26484634/24044073/7992d24e-0b11-11e7-8ac1-53cbb4b8d43f.png)

![image](https://cloud.githubusercontent.com/assets/26484634/24044130/d10ed716-0b11-11e7-85d7-c673243da578.png)

Any ideas?

Many thanks in advance.

**Comment by kgeorgiou** [comment]
Was that on a Blank Gameweek?
